# Generated by Django 5.0.2 on 2024-02-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('app2', '0001_initial'), ('app2', '0002_nbaplayer_nationality')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nbaPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('agilityScore', models.IntegerField()),
                ('nationality', models.CharField(default=1, max_length=255)),
            ],
        ),
    ]
