# Generated by Django 5.0.2 on 2024-02-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbaplayer',
            name='nationality',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
