# Generated by Django 5.0.2 on 2024-02-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sui',
            field=models.IntegerField(default=1),
        ),
    ]
